import test from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/website-checkout.js';
const body={name:'Test Person',email:'person@example.test',phone:'+44 7700 900123',consent:true,requestId:'12345678-1234-1234-1234-123456789012'};
const res=()=>({statusCode:200,setHeader(){},status(n){this.statusCode=n;return this},json(data){this.body=data;return this}});
const req=(b=body)=>({method:'POST',headers:{host:'scale.cr8or.ai',origin:'https://scale.cr8or.ai'},body:b});
const originalFetch=global.fetch;
const originalEnv={GHL_API_KEY:process.env.GHL_API_KEY,STRIPE_SECRET_API_KEY:process.env.STRIPE_SECRET_API_KEY};
test.beforeEach(()=>{process.env.GHL_API_KEY='mock';process.env.STRIPE_SECRET_API_KEY='mock';});
test.afterEach(()=>{global.fetch=originalFetch;for(const [key,value] of Object.entries(originalEnv)){if(value===undefined)delete process.env[key];else process.env[key]=value;}});
function upstream(calls=[],failStripe=false){global.fetch=async(url,options)=>{calls.push({url,options});if(url.includes('stripe.com')){if(failStripe)return new Response('{}',{status:500});return new Response(JSON.stringify(url.endsWith('customers')?{id:'cus_test'}:{id:'cs_test',url:'https://checkout.stripe.com/c/pay/test'}));}return new Response(JSON.stringify({contact:{id:'contact_1'}}));};return calls;}
test('invalid input and cross-origin requests never save leads or create payments',async()=>{global.fetch=()=>{throw Error('Unexpected fetch')};for(const b of [null,{...body,email:'bad'},{...body,phone:'123'},{...body,consent:false},{...body,website:'bot'},{...body,requestId:'bad'}]){const r=res();await handler(req(b),r);assert.equal(r.statusCode,400)}const q=req();q.headers.origin='https://other.test';const r=res();await handler(q,r);assert.equal(r.statusCode,403)});
test('checkout saves lead first, locks £49 monthly, prefills all details and retries idempotently',async()=>{const calls=upstream();for(let i=0;i<2;i++){const r=res();await handler(req({...body,amount:1,currency:'usd',success_url:'https://other.test'}),r);assert.equal(r.statusCode,200)}assert.match(calls[0].url,/contacts\/upsert/);const customers=calls.filter(x=>x.url.endsWith('customers'));assert.equal(customers[0].options.body.get('phone'),body.phone);assert.equal(customers[0].options.body.get('name'),body.name);const sessions=calls.filter(x=>x.url.endsWith('checkout/sessions'));const p=sessions[0].options.body;assert.equal(p.get('mode'),'subscription');assert.equal(p.get('line_items[0][price_data][unit_amount]'),'4900');assert.equal(p.get('line_items[0][price_data][currency]'),'gbp');assert.equal(p.get('line_items[0][price_data][recurring][interval]'),'month');assert.match(p.get('success_url'),/^https:\/\/scale.cr8or.ai\/websites\//);assert.equal(sessions[0].options.headers['Idempotency-Key'],sessions[1].options.headers['Idempotency-Key']);});
test('Stripe failure preserves the saved lead and gives a retry message',async()=>{upstream([],true);const r=res();await handler(req(),r);assert.equal(r.statusCode,503);assert.match(r.body.error,/details are saved/)});
test('CRM failure prevents checkout',async()=>{const calls=[];global.fetch=async url=>{calls.push(url);return new Response('{}',{status:500})};const r=res();await handler(req(),r);assert.equal(r.statusCode,503);assert.equal(calls.length,1)});
test('confirmation checks Stripe payment, offer and amount rather than URL claims',async()=>{for(const [session,expected,paid] of [[{metadata:{offer:'bespoke-website-49'},currency:'gbp',amount_total:4900,status:'complete',payment_status:'paid'},200,true],[{metadata:{offer:'bespoke-website-49'},currency:'gbp',amount_total:4900,status:'open',payment_status:'unpaid'},200,false],[{metadata:{offer:'other'},currency:'gbp',amount_total:4900},404,undefined],[{metadata:{offer:'bespoke-website-49'},currency:'gbp',amount_total:49},404,undefined]]){global.fetch=async()=>new Response(JSON.stringify(session));const r=res();await handler({method:'GET',query:{session_id:'cs_test_abcdefghijklmnopqrstuvwxyz'}},r);assert.equal(r.statusCode,expected);assert.equal(r.body.paid,paid)}});
